trade-center:
  item:
    can-craft: true
    name: "&eTrade Center"
    lore: "&7Right-click when placed to view nearby villagers' trades."
  message:
    execute-cmd-no-permission: "&cYou don't have permission to execute this command!"
    use-no-permission: "&cYou don't have permission to use this!"
    already-in-use: "&cThis trade center is currently being used by another player!"
    no-villagers-nearby: "&cThere are no nearby villagers!"
    invalid-trade: "&cThis trade no longer exists!"
  display-cache:
    auto-reloader-timer: 5
    auto-reloader-radius: 2 # -1 to disable
    chunk-listener-radius: 2 # -1 to disable